// <auto-generated />
namespace WAT.Admin.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class PaxTableModification : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(PaxTableModification));
        
        string IMigrationMetadata.Id
        {
            get { return "201607082015087_PaxTableModification"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
